### ISSUE TITLE
Warns about webpack-hot-middleware

### ISSUE THREAD

**Issue by sapegin** [kentcdodds/webpack-validator#6] opened 2016-02-22 07:53 UTC
In Webpack config:

```
entry: [
	'webpack-hot-middleware/client',
	path.join(__dirname, 'index');
],
```

Validation result:

```
entry: no file exists at /Users/tema/Dropbox/Projects/_Repos/react-styleguidist/webpack-hot-middleware/client - no file exists at /Users/tema/Dropbox/Projects/_Repos/react-styleguidist/src/index
```

**Comment by kentcdodds** [comment] 2016-02-22 08:08
Hi @sapegin! Thanks for your interest in the project. This is a duplicate of #3...

I think that the real solution is to still check for the existence of a resolvable file, but only if the entry filename doesn't contain a query string or `webpack-hot-middleware` do you think that would cover all cases?

**Comment by kentcdodds** [comment] 2016-02-22 08:09
Let's move discussion over to #3. Thanks!

**Closed by kentcdodds** 2016-02-22 08:09 UTC
