### ISSUE TITLE
Entry > Vendors not finding npm package?

### ISSUE THREAD

**Issue by Krisa** [kentcdodds/webpack-validator#10] opened 2016-02-26 11:42 UTC
I have a config listing vendors, similar to the example shown on the page: https://webpack.github.io/docs/code-splitting.html with simply the name of the npm modules listed like here:
```
entry: {
    vendor: ["jquery", "underscore", ...],
},..
```

However, I get a validation error, that `entry: no file exists at .........../jquery` for example. Indeed, it doesn't consider that jquery is a npm module and look simply at the root of my project whether it exists a jquery.js file.

**Comment by kentcdodds** [comment] 2016-02-26 15:23
Hi @Krisa!

Thanks for your interest in the project. This is still in beta so I appreciate your patience. This is a duplicate of #3, so I'll go ahead and close it.

**Closed by kentcdodds** 2016-02-26 15:23 UTC
